name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no index.html ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
